In [13]:
import numpy as np

# Accesos a la información

## Acceso a un vector

In [14]:
vector = np.array([1,2,3,4,5,6,7])
print(vector)

[1 2 3 4 5 6 7]


In [15]:
print(vector[3])
print(vector[-1])
print(vector[2:5])
print(vector[2:5:2]) # Aquí podemos elegir los elementos de 2 a 5, de dos en dos.

4
7
[3 4 5]
[3 5]


## Acceso a una matriz de dos dimensiones

In [16]:
array_2_dim = np.array([[1,2,3],[4,5,6]])
print(array_2_dim)

[[1 2 3]
 [4 5 6]]


In [17]:
print(array_2_dim[1,2])

6


## Acceso a una matriz de tres dimensiones

In [18]:
array_3_dim = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_3_dim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
print(array_3_dim[1,1,2])

12


In [20]:
a = 4

In [21]:
b = a

In [22]:
print(id(a))
print(id(b))

2446186277264
2446186277264


In [23]:
a = 5

In [24]:
print(id(a))
print(id(b))

2446186277296
2446186277264
