# Matrices

In [1]:
import numpy as np

### Matriz cero

In [10]:
vectorZeros = np.zeros(((4)))
vectorZeros

array([0., 0., 0., 0.])

In [8]:
zeros = np.zeros((3,4)) 
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# Se puede agregar el tipo de dato para que no sea de tipo flotante
# uint8 es el que más se acerca, "u" no aparecen números negativos, "int" para que sean enteros y "8"
# para que tenga máximo 8 bytes. 
zeros = np.zeros((3,4),np.uint8)
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [11]:
zeros = np.zeros((3,4,5),np.uint8)
zeros

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=uint8)

### Matriz unidad

In [7]:
ones = np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Matriz identidad

In [16]:
matrizIdentity = np.identity((12))
matrizIdentity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Reshape

In [17]:
ndArray = np.array([2,3,4,5,6,7])
ndArray

array([2, 3, 4, 5, 6, 7])

In [19]:
ndArray.reshape(6,1)

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [21]:
# puedo hacerlo asi
ndArray = np.array([12,13,41,52,26,17]).reshape(3,2)
ndArray

array([[12, 13],
       [41, 52],
       [26, 17]])

In [37]:
reshape = np.arange(225).reshape(75,-1)
reshape

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26],
       [ 27,  28,  29],
       [ 30,  31,  32],
       [ 33,  34,  35],
       [ 36,  37,  38],
       [ 39,  40,  41],
       [ 42,  43,  44],
       [ 45,  46,  47],
       [ 48,  49,  50],
       [ 51,  52,  53],
       [ 54,  55,  56],
       [ 57,  58,  59],
       [ 60,  61,  62],
       [ 63,  64,  65],
       [ 66,  67,  68],
       [ 69,  70,  71],
       [ 72,  73,  74],
       [ 75,  76,  77],
       [ 78,  79,  80],
       [ 81,  82,  83],
       [ 84,  85,  86],
       [ 87,  88,  89],
       [ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124

# Linspace

In [56]:
np.linspace(0,5,25) # primer valor del argumento: valor inicial, segundo: valor final, tercero: cantidad de valores

array([0.        , 0.20833333, 0.41666667, 0.625     , 0.83333333,
       1.04166667, 1.25      , 1.45833333, 1.66666667, 1.875     ,
       2.08333333, 2.29166667, 2.5       , 2.70833333, 2.91666667,
       3.125     , 3.33333333, 3.54166667, 3.75      , 3.95833333,
       4.16666667, 4.375     , 4.58333333, 4.79166667, 5.        ])

# Random

In [57]:
np.random.random((3,5))

array([[0.07908051, 0.13746834, 0.802189  , 0.10802945, 0.57695974],
       [0.25723107, 0.55709177, 0.56329486, 0.44578319, 0.24928914],
       [0.80299719, 0.01734869, 0.55171432, 0.11431642, 0.71712481]])

# Producto cruz 

In [59]:
arrayA = np.array([
    [4,5,6],
    [1,2,1]
])

arrayB = np.array([
    [1,1],
    [1,2],
    [5,9]
])
arrayA, arrayB

(array([[4, 5, 6],
        [1, 2, 1]]),
 array([[1, 1],
        [1, 2],
        [5, 9]]))

In [61]:
arrayA.dot(arrayB)

array([[39, 68],
       [ 8, 14]])

# Funciones Universales

In [66]:
arrayTrigonometria = np.array([0,39,45,60,90,180,270,360])
arrayTrigonometria

array([  0,  39,  45,  60,  90, 180, 270, 360])

In [79]:
np.sin(arrayTrigonometria)
np.cos(arrayTrigonometria)
np.tan(arrayTrigonometria)

array([ 0.        ,  3.61455441,  1.61977519,  0.32004039, -1.99520041,
        1.33869021, -0.17883906, -3.38014041])

In [77]:
array_mock = np.array([1,2,3,4,5,6,7,8,9,10])
array_mock.sum()
array_mock.min()
array_mock.max()
array_mock.mean()
array_mock.min()
array_mock.max()
array_mock.std()

2.8722813232690143