In [2]:
import numpy as np

# Array

### Es una colección de elementos del mismo tipo ordenados

In [5]:
arrayA = np.array([1,2,3,4,5,6])
print(arrayA), print(type(arrayA))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


(None, None)

### otra forma de crear array

In [7]:
arrayB = np.array((1,2,3,4,5,6))
print(arrayB), print(type(arrayB))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


(None, None)

### Todos los elementos del ndarray deben ser del mismo tipo

In [12]:
arrayC = np.array(["1","2","3","4","5",6,3+2j])
arrayC

array(['1', '2', '3', '4', '5', '6', '(3+2j)'], dtype='<U64')

# Dimensiones de un array

## 1 dimension

In [19]:
array_1 = np.array([1,2,3,4,5])
print(array_1)

[1 2 3 4 5]


In [22]:
print("total de elementos",array_1.size), print(array_1.shape), print(array_1.dtype), print(array_1.ndim)

total de elementos 5
(5,)
int32
1


(None, None, None, None)

## 2 dimensiones

## 3 dimensiones