# Regresión Logística con Data Set desde un url

In [6]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

url = "https://raw.githubusercontent.com/Statology/Python-Guides/main/default.csv"

In [4]:
url = "https://raw.githubusercontent.com/Statology/Python-Guides/main/default.csv"
data = pd.read_csv(url)
data.head()

default  student      balance        income
0        0        0   729.526495  44361.625074
1        0        1   817.180407  12106.134700
2        0        0  1073.549164  31767.138947
3        0        0   529.250605  35704.493935
4        0        0   785.655883  38463.495879

In [7]:
data[0:6] #ver una cantidad de filas

default  student      balance        income
0        0        0   729.526495  44361.625074
1        0        1   817.180407  12106.134700
2        0        0  1073.549164  31767.138947
3        0        0   529.250605  35704.493935
4        0        0   785.655883  38463.495879
5        0        1   919.588530   7491.558572

In [8]:
len(data) #longitud de nuestra data

10000

# Estimando el modelo de Rgresión Logística

In [10]:
X = data[['student','balance','income']] #variables predictoras
y = data[['default']] # variable de respuesta

In [11]:
X

student      balance        income
0           0   729.526495  44361.625074
1           1   817.180407  12106.134700
2           0  1073.549164  31767.138947
3           0   529.250605  35704.493935
4           0   785.655883  38463.495879
...       ...          ...           ...
9995        0   711.555020  52992.378914
9996        0   757.962918  19660.721768
9997        0   845.411989  58636.156984
9998        0  1569.009053  36669.112365
9999        1   200.922183  16862.952321

[10000 rows x 3 columns]

In [12]:
y

default
0           0
1           0
2           0
3           0
4           0
...       ...
9995        0
9996        0
9997        0
9998        0
9999        0

[10000 rows x 1 columns]

In [13]:
# Dividir la data en train 70% y testing 30%
# Primero conjunto de entrenamiento y luego el conjunto testing o validación
# tanto en X como en y.
# Luego se hace el comando para crear el conjunto de entrenamiento y validación
# Primero se escribe la X luego y y después el tamaño de el testing (30%)
# Finalmente con random, creamos un estado aleatorio para que cuando 
# corra la data siempre nos de el mismo resultado.
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 0)

In [14]:
# Instanciamos el modelo
log_regression = LogisticRegression()

In [15]:
# Ajustar el modelo usando el training
log_regression.fit(X_train, y_train)

C:\Users\Danko\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [16]:
# Ahora haremos predicciones
y_pred = log_regression.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [17]:
# Diagnóstico del modelo
cnf_matrix = metrics.confusion_matrix(y_test,y_pred) # esta es la matriz de confusión sirve para ver cuantos datos pronosticó bien y cuantos equivocados
cnf_matrix

array([[2870,   17],
       [  93,   20]], dtype=int64)

In [18]:
print('Accuracy:', metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.9633333333333334


# Ahora pronosticaremos un nuevo caso

In [19]:
# [[estudiante, dinero en la cuenta,]]
log_regression.predict([[0,729,44361]])

C:\Users\Danko\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

# Si necesito los coeficientes

In [20]:
log_regression.coef_

array([[-3.79999456e+00,  4.03495132e-03, -1.36823955e-04]])

In [21]:
log_regression.intercept_

array([-2.86843745])