# REGRESIÓN LINEAL MÚLTIPLE

## Conceptos
- Root mean squared error (RMSE): la raíz cuadrada del error cuadrático promedio de la regresión (esta es la métrica más utilizada para comparar modelos de regresión).
- Residual standard error: Igual que la raíz del error cuadrático medio, pero ajustado por grados de libertad.
- R-squared (COEFICIENTE DE DETERMINACIÓN): La proporción de varianza explicada por el modelo, de 0 a 1.
- T-statistic: El coeficiente de un predictor, dividido por el error estándar del coeficiente, lo que proporciona una métrica para comparar la importancia de las variables en el modelo.
- Weighted regression: Regresión con los registros teniendo diferentes pesos.

In [26]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm

In [2]:
data = pd.read_csv("insurance.csv")
data

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
# predictors = ['age', 'sex','smoker','children','bmi', 'region']
predictors = ['age','children','bmi']
outcome = 'charges'
insurance_lm = LinearRegression()
insurance_lm.fit(data[predictors],data[outcome])

LinearRegression()

In [4]:
# Intercepto
intercepto = insurance_lm.intercept_
intercepto

-6916.243347787036

In [5]:
for name, coef in zip(predictors, insurance_lm.coef_):
    print(f'{name}:{coef}')

age:239.99447429364636
children:542.8646522470178
bmi:332.0833645034481


In [6]:
insurance_lm.predict(pd.DataFrame({
    'age': [24],
    'children': [0],
    'bmi': [22.5]
}))

array([6315.49973659])

In [7]:
insurance_lm.predict(pd.DataFrame({
    'age': [24,28,25],
    'children': [0,0,0],
    'bmi': [22.5,20,25]
}))

array([6315.49973659, 6445.2692225 , 7385.70262214])

# Raíz cuadrada del error cuadrático promedio de la regresión

In [8]:
fitted = insurance_lm.predict(data[predictors])
fitted

array([ 6908.77753344,  9160.97706103, 12390.94691779, ...,
        9640.92917145,  6691.39141657, 17377.08299024])

In [13]:
RMSE = np.sqrt(np.sum((data[outcome]-fitted)**2)/fitted.size)
RMSE

11355.317901125973

### También se puede obtener importándolo desde --> from sklearn.metrics import mean_squared_error

In [21]:
RMSE_sklearn = np.sqrt(mean_squared_error(data[outcome],fitted))
RMSE_sklearn

11355.317901125973

# Librería de metodos estadísticos --> pip install statsmodels
## Luego de instalarlo debemos importarlo --> import statsmodels as sm

In [24]:
pip install statsmodels

Note: you may need to restart the kernel to use updated packages.


In [27]:
insurance_sm = sm.OLS(data[outcome],data[predictors])
results = insurance_sm.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                charges   R-squared (uncentered):                   0.596
Model:                            OLS   Adj. R-squared (uncentered):              0.595
Method:                 Least Squares   F-statistic:                              655.7
Date:                Wed, 07 Sep 2022   Prob (F-statistic):                   6.52e-262
Time:                        23:38:23   Log-Likelihood:                         -14400.
No. Observations:                1338   AIC:                                  2.881e+04
Df Residuals:                    1335   BIC:                                  2.882e+04
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
age          205.5096     20.605      9.974      0.000     165.088     245.931
children     407.6827    257.331      1.584      0.113     -97.135     912.501
bmi          162.5084     28.007      5.802      0.000     107.566     217.451
==============================================================================
Omnibus:                      369.789   Durbin-Watson:                   2.018
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              750.403
Skew:                           1.648   Prob(JB):                    1.13e-163
Kurtosis:                       4.610   Cond. No.                         42.2
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

## NOTA: un "estadístico t" alto y un "p valor" bajo, indica que la variable es más significante que las otras.